GET http://localhost:5000/auth/books
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODA5MjU2NjcsImV4cCI6MTY4MDkyNTY5N30.JGlTH9T4Yvftpm3gz_gOn2N87m46jRxpM_fVD9HfzIA

###
POST http://localhost:5000/auth/login
Content-Type:  application/json

{
    "username": "TanKhoa"
}